import type { Metadata } from "next";
import {
  Dancing_Script,
  Fondamento,
  Geist,
  Geist_Mono,
  Playfair,
  Playfair_Display,
  Poppins,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const dancingScript = Dancing_Script({
  variable:"--dancing-script-var",
  subsets:["latin"]
})
const poppins = Poppins({
  variable: "--font-poppins-var",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
});
const fondamento = Fondamento({
  variable: "--font-fondamento-var",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Restaurant Branding",
  description: "Generated by Devansh Raghav",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dancingScript.variable} ${poppins.variable} ${fondamento.variable}  antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
